# version docker-compose
version: '3.1'
services:

    app:
        container_name: app-springboot-postgresql
        image: app-springboot-postgresql
        build: ./
        # ports
        ports:
            - "8080:8080"
        # mount dirs, left - host machine, right - in container
        depends_on:
             - dbpostgresql
        links:
            - dbpostgresql

    dbpostgresql:
        image: andreechka/postgres_my:ver13.0_base_inside
        ports:
            - "5433:5432"
        env_file:
            - env.list

#        environment:
#           - POSTGRES_PASSWORD=123qwe
#            - POSTGRES_USER=ruser
#            - POSTGRES_DB=services
#            - PGDATA=/var/lib/postgresql/data/pgdata

